### ISSUE TITLE
Downloading UCF-101 data error

### ISSUE THREAD

**Issue by slerman12** [wilson1yan/VideoGPT#5]
I ran the provided script and received this error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ucf101/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi' -> 'datasets/ucf101/train/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/preprocess/ucf_split_train_test.py", line 20, in <module>
    move_files(train_files, 'train')
  File "scripts/preprocess/ucf_split_train_test.py", line 16, in move_files
    shutil.move(osp.join(root, 'UCF-101', filename), osp.join(split_dir, filename))
  File "/u/slerman/miniconda3/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/u/slerman/miniconda3/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/u/slerman/miniconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/ucf101/UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01.avi'
rm: cannot remove 'datasets/ucf101/UCF-101': No such file or directory
```

**Comment by wilson1yan** [comment]
I believe this error happens when one of `unrar` and `unzip` is not installed
